project:
  type: website
  output-dir: docs

website:
  title: <img class="circular_image" src="https://avatars.githubusercontent.com/u/84399192" width="7%" height="7%" /> Blog
  navbar:
    right:
      - posts.qmd
      - about.qmd
      - icon: github
        href: https://github.com/erikscheurer
format:
  html:
    theme: simplex
    css: styles.css
